---
title: "ONC_filtering"
author: "Jorge H."
date: "25/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(reticulate)
library(readr)
library(data.table)
```


```{r}
#Creating a variable to record in memory package 'pandas' with its functions.
pandas_imp <- import("pandas")
  #Need to use py_install("pandas")

#Reading pickle file.
pickle_ONC_HP_DDIs <- pandas_imp$read_pickle("Data/onchighpriority-ddis.pickle")

#Converting pickle file in data frame (Needs to be called twice the as.data.frame).
pickle_ONC_HP_DDIs <- t(as.data.frame(
  lapply(pickle_ONC_HP_DDIs, 
         function(x){
           return(c(x$drug2, x$drug1, x$source, x$precipitant, x$object))
           }
         )
  ))

pickle_ONC_HP_DDIs <- as.data.frame(pickle_ONC_HP_DDIs)


#Modifying labels.
rownames(pickle_ONC_HP_DDIs) <- NULL
colnames(pickle_ONC_HP_DDIs) <- c("Drug1","Drug2","Source","Precipitant","Object")

pickle_ONC_HP_DDIs$Drug1 <- gsub("http://bio2rdf.org/drugbank:","",pickle_ONC_HP_DDIs$Drug1)
pickle_ONC_HP_DDIs$Drug2 <- gsub("http://bio2rdf.org/drugbank:","",pickle_ONC_HP_DDIs$Drug2)


  # Small change in first row "﻿"
pickle_ONC_HP_DDIs$Object[1] <- gsub("﻿","",pickle_ONC_HP_DDIs$Object[1])

```


ATC
```{r}
Drug_ATC_codes_DB <- read_csv("Data/Drug_ATC_codes_DB.csv")

DDI_mapped <- merge(
  pickle_ONC_HP_DDIs,
  Drug_ATC_codes_DB[,c(1,10)],
  by.x="Drug1",
  by.y = "parent_key"
  )

DDI_mapped <- merge(
  DDI_mapped,
  Drug_ATC_codes_DB[,c(1,10)], 
  by.x="Drug2",
  by.y = "parent_key"
  )

# Adding proper names
setnames(DDI_mapped,
         old = c("atc_code.x","atc_code.y"),
         new = c("drug", "codrug")
         )

# Adding columns of first level of ATC
DDI_mapped$level_1_atc_drug <- substr(DDI_mapped$drug,1,1)
DDI_mapped$level_1_atc_codrug <- substr(DDI_mapped$codrug,1,1)

# Unifying ATC colums so to have them as vectors also
DDI_mapped$ATC_vector <- paste(
  DDI_mapped$drug,DDI_mapped$codrug,
  sep = "_"
  ) 
```

Factorising *Clinical significance*, *Management*, *Evidence level* features.
```{r}
DDI_mapped$Clinical_significance <- "Highly_significant"

DDI_mapped$Management <- "Contraindicated"

DDI_mapped$Evidence_level <- "Documented_case_reports"

# Saving tables with preferred sortening
DDI_mapped <- DDI_mapped[,c(6,7,2,1,4,5,11,12,13,8,9,10)]
```

Filtering ONC high priority DDIs that can be observed in the clinical data
```{r}
clinicaldrugpairs_counts <- read_delim("Data//clinicaldrugpairs_counts.tsv",
                                       "\t", 
                                       escape_double = FALSE, 
                                       trim_ws = TRUE)


DDI_mapped_subset <- merge(DDI_mapped,
                           clinicaldrugpairs_counts[,1:2],
                           by = c("drug", "codrug")
                           )
```


Saving table with all information for compendia and clinical data
```{r}
# Compendia
write.table(DDI_mapped,
            "C:/Users/Jorge_TEMP/Desktop/Thesis_Bibliography/DDI_datasets/ATC_treatment/Filtered_datasets/ONC_HIGH_to_ATC.txt",
            sep = "\t",
            row.names = FALSE, 
            col.names = FALSE)

# Clinical data
write_csv(DDI_mapped_subset,
          "C:/Users/Jorge_TEMP/Desktop/Thesis_Bibliography/DDI_datasets/Analysis/ATC_treatment/DDI_clinical_data/DDI_dataset/ONC-high_DDI.txt")
```

Saving ATC vector for clinical data
```{r}
#Clinical data
filese <- file("C:/Users/Jorge_TEMP/Desktop/Thesis_Bibliography/DDI_datasets/Analysis/ATC_treatment/DDI_clinical_data/DDI_atc_vector/ONC-high_vector.txt")
writeLines(c(DDI_mapped_subset$ATC_vector), filese)
close(filese)
```

Saving datasets with their respective *feature* column for clinical data
```{r}
# Saving all DDIs with the feature clinical significance
write_csv(DDI_mapped_subset[,c(1,2,7,10,11)],
          "C:/Users/Jorge_TEMP/Desktop/Thesis_Bibliography/DDI_datasets/Analysis/Features/Clinical_significance/ONC-high_clinical_significance_DDI.txt",
          col_names = FALSE)

  # Saving all DDIs with the feature management
write_csv(DDI_mapped_subset[,c(1,2,8,10,11)],
          "C:/Users/Jorge_TEMP/Desktop/Thesis_Bibliography/DDI_datasets/Analysis/Features/Management/ONC-high_management_DDI.txt",
          col_names = FALSE)

# Saving all DDIs with the feature evidence level
write_csv(DDI_mapped_subset[,c(1,2,9:11)],
          "C:/Users/Jorge_TEMP/Desktop/Thesis_Bibliography/DDI_datasets/Analysis/Features/Evidence_level//ONC-high_evidence_level_DDI.txt",
          col_names = FALSE)

```

